### ISSUE TITLE
Any advantages over serde_json?

### ISSUE THREAD

**Issue by dtolnay** [maciejhirsz/json-rust#1]
I came across this library on crates.io and I am curious. Maybe call out the advantages in the readme.

**Comment by maciejhirsz** [comment]
Thanks! I'll keep updating the readme and host docs online as soon as I've some time :).

For starters - this lib has no dependencies and works on stable Rust.

**Comment by maciejhirsz** [comment]
Wrote down some foreword in the README now, hopefully sufficient:
https://github.com/maciejhirsz/json-rust#why

Gonna close the issue, but feel free to comment on.
