### ISSUE TITLE
Raw pointer prevents me from using threads

### ISSUE THREAD

**Issue by voider1** [maciejhirsz/json-rust#100]
I was trying to use threading with this JSON module and I couldn't compile because there's a raw pointer [here](http://json.rs/doc/src/json/src/object.rs.html#18). It also only implements Sync, but not Send. I assume the library is thread safe and is only missing a Send?

**Comment by maciejhirsz** [comment]
Thanks! This should be easy to fix, will add the `Send` marker.

**Comment by voider1** [comment]
@maciejhirsz Alright, amazing!

**Comment by maciejhirsz** [comment]
@voider1 released a fix. Sorry for taking so long, just flew back from holidays, jet lag and all that.

Closing the issue.

**Comment by voider1** [comment]
@maciejhirsz Amazing!
