### ISSUE TITLE
SIGSEGV

### ISSUE THREAD

**Issue by maciejhirsz** [maciejhirsz/json-rust#103]
Need to find a way to reproduce, as it apparently happens on stable Rust: https://github.com/rust-lang/rust/issues/38687

**edit:** running `cargo test --test value` reproduces the issue

**Comment by meh** [comment]
@maciejhirsz you should try and use american fuzzy lop, it works wonders, would you accept a pull request that sets that up?

**Comment by maciejhirsz** [comment]
Would definitely accept a PR. Even if it can't find this particular issue, there had been others issues in the past.

**Comment by dtolnay** [comment]
I wonder what is changing on the compiler side to affect this. On my computer:

```bash
while cargo +1.12.0 test --test value; do :; done # does not fail
while cargo +1.13.0 test --test value; do :; done # does not fail
while cargo +1.14.0 test --test value; do :; done # fails almost immediately
while cargo +beta test --test value; do :; done # fails almost immediately
while cargo +nightly test --test value; do :; done # does not fail
```

**Comment by maciejhirsz** [comment]
Interesting thing is that I'm unable to reproduce it on OSX, but I can reproduce it on a Linux machine.

**Comment by maciejhirsz** [comment]
Identified the problem. I was playing with fire and got humbled by the compiler once I tried rewriting `object.rs` to safe rust at cost of performance to see if that eliminates the segfault.

I wrongly attributed the borrow lifetimes to be call scope instead of bound to the `Node` here:
https://github.com/maciejhirsz/json-rust/blob/9eabb9069face119e1d170bd8a445c57177d432a/src/object.rs#L100-L112

Fix and new release should follow shortly.
