### ISSUE TITLE
Implement Index for Object

### ISSUE THREAD

**Issue by hobofan** [maciejhirsz/json-rust#104]
Sometimes I like to pass around JSON `Object`'s after filtering them out of a bigger JSON structure.

As it stands right now, if I want to access its fields with the same easy indexing syntax, I first have to put i `JsonValue` again, which feels kind of pointless.

Would you accept a PR that also implements `Index` directly for `Object`?

**Comment by maciejhirsz** [comment]
That sounds perfectly reasonable and should be pretty easy to do. If you'd like to commit a PR for that I'd more than welcome it :).
