### ISSUE TITLE
Out of bounds access when parsing 0 at end of input

### ISSUE THREAD

**Issue by dtolnay** [maciejhirsz/json-rust#106]
Adding `assert!(self.index < self.length)` to `Parse::read_byte` catches this.

Example inputs that trigger the bug:

- `0`
- `-0`
- `[0`
- `{"":0`

**Comment by dtolnay** [comment]
```rust
extern crate json;

use std::str;

fn main() {
    let data = b"0.123456789";
    let s = str::from_utf8(&data[..1]).unwrap();
    println!("{:?}", s);
    println!("{:?}", json::parse(s));
}
```

```
"0"
thread 'main' panicked at 'byte index 12 is out of bounds of `0`', /checkout/src/libcore/str/mod.rs:1775
```

**Comment by maciejhirsz** [comment]
Thanks!

I've added a `debug_assert` for the future. I've been plotting a pretty major rewrite based on some experience I got by now when dealing with another project. Not very happy about code quality in the parser here.
