### ISSUE TITLE
Could we teach object! to accept trailing commas

### ISSUE THREAD

**Issue by Yoric** [maciejhirsz/json-rust#125]
Right now,

```rust
object!{
  "foo" => "bar",
}
```

fails because of the trailing comma. It would be nicer to accept them, as in the rest of Rust.

**Comment by maciejhirsz** [comment]
Last time I tried it the macro layout wasn't very happy about it, but I will look into it again.

**Comment by Yoric** [comment]
I can give it a try this week-end, if you want.

**Comment by maciejhirsz** [comment]
Sure, always happy to accept contributions. I'm currently _swarmed_ with work.
