### ISSUE TITLE
slashes in the .dump() and .pretty() output are escaped

### ISSUE THREAD

**Issue by imp** [maciejhirsz/json-rust#14]
output generated by .dump() and .pretty() has all the slashes ("/") symbols escaped with backslash ("\") - like that - 
```json
{
    "path": "\/etc\/motd"
}
```
That doesn't seem to be pretty [as name may imply :)]. Probably an artifact of the internal conversion. I think the backslashes should be dropped.

**Comment by maciejhirsz** [comment]
Note to self: drink coffee before committing to master.
