### ISSUE TITLE
How to serialize a JsonValue into a compact binary format?

### ISSUE THREAD

**Issue by zhengyi-yang** [maciejhirsz/json-rust#151]
I am implementing a NoSQL database that uses `JsonValue` as its basic storage block. However, I am wondering if there is anyway that I can serialize a `JsonValue` into a compact binary format instead of `String` (using `Serde` and `bincode` for example)?

**Comment by maciejhirsz** [comment]
If your database uses plain json text, you can deserialize it to [`serde_json::Value`](https://docs.serde.rs/serde_json/enum.Value.html) instead of `JsonValue` from this crate, and then serialize that to binary using `bincode`.

**Comment by zhengyi-yang** [comment]
Thanks

**Comment by maciejhirsz** [comment]
Cheers :)
