### ISSUE TITLE
Printable JsonValue

### ISSUE THREAD

**Issue by imp** [maciejhirsz/json-rust#16]
I would like to suggest adding std::fmt::Display trait to JsonValue to make it printable.
For example `"{}"` will print `json.dump()` and `"{:#}"` - `json.pretty()`

**Comment by maciejhirsz** [comment]
@imp I think that's a pretty neat idea. I'd only add an exception that if the root of what you want to print is not an object or an array, it prints out the underlying value.

Basically:

```rust
let data = array!["foo"];
println!("{}", data[0]);
```

Should print out `foo` without quotes.

**Comment by Mark-Simulacrum** [comment]
I'm not sure the default setting of 2 for the indentation when the [Rust style guide](https://github.com/rust-lang/rust/blob/master/src/doc/style/style/whitespace.md) (admittedly, for Rust code) specifies 4 spaces.

Perhaps we can utilize the [width parameter](https://doc.rust-lang.org/std/fmt/#width) (although this isn't really what it was intended for) in `std::fmt`? I'm not sure how to access those, however.

**Comment by maciejhirsz** [comment]
Yeah, I'd also stick to 4 spaces as default to keep in line with derived debug `{:#?}`.

**Comment by imp** [comment]
width can be queried with f.width() (surprise !) like this
```rust
fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
    let width = f.width().unwrap_or(4);
    // use width as you see fit
}
```
As for default indent value being 2 or 4 or any other value - I have no preference. I see that jsonprettyprint.com formats with indent=2. However, other tools (python json.tool for example) defaults to indent=4. As long as there is a sane default and a method for overriding it - I do not care.

**Comment by maciejhirsz** [comment]
FYI - while the issue got closed, I am still considering using the width to customize pretty print indents.
