### ISSUE TITLE
cannot borrow variables in object!

### ISSUE THREAD

**Issue by ardawan** [maciejhirsz/json-rust#160]
I'm trying to create my data object and serialize it for sending through my network. but I'm not able to borrow "src" in my object.
I need the src to use it in the send_to() method.

is that a bug or the structure should be this way only?

```
let mut data = object!{
    "HEADER" => "RES:REGISTER",
    "SOURCE" => &src,
    "BODY" => object!{
        "UUID" => reg_serial
    }
};

// even i've tried this
//data["SOURCE"] = &src.into(); 

let serialised_data = json::stringify(data);
socket.send_to(&serialised_data.into_bytes(), &src).expect("cannot send");
```

the error is
```
error[E0277]: the trait bound `json::value::JsonValue: std::convert::From<&std::string::String>` is not satisfied
   --> src/main.rs:95:20
    |
95  |       let mut data = object!{
    |  ____________________^
96  | |         "HEADER" => "RES:REGISTER",
97  | |         "SOURCE" => &src,
98  | |         "BODY" => object!{
99  | |             "UUID" => reg_serial
100 | |         }
101 | |     };
    | |_____^ the trait `std::convert::From<&std::string::String>` is not implemented for `json::value::JsonValue`
    |
    = help: the following implementations were found:
              <json::value::JsonValue as std::convert::From<bool>>
              <json::value::JsonValue as std::convert::From<i8>>
              <json::value::JsonValue as std::convert::From<isize>>
              <json::value::JsonValue as std::convert::From<usize>>
            and 17 others
    = note: required because of the requirements on the impl of `std::convert::Into<json::value::JsonValue>` for `&std::string::String`
    = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)

error: aborting due to previous error
```

**Comment by maciejhirsz** [comment]
Try `src.as_str()` instead of `&src`.

**Comment by ardawan** [comment]
> Try `src.as_str()` instead of `&src`.

doesn't work. i got this error
```
src.as_str(),
    ^^^^^^ help: there is a method with a similar name: `as_ptr`
```

**Comment by maciejhirsz** [comment]
1. What is the type of `src`? if it were a `String` you should be able to convert it to a `str` slice with `.as_str()`.
2. Macro won't be able to handle a mutex guard for you, you need to get a raw Vec that satisfies the [available `From` implementations for `JsonValue`](https://docs.rs/json/0.11.14/json/enum.JsonValue.html#implementations). Just looking at the list now, regular slices are missing, so I can add that for convenience.

**Comment by ardawan** [comment]
> 1. What is the type of src? if it were a String you should be able to convert it to a str slice with .as_str().

The str is already a String type. that's why at first i just reference it rather than converting to str.

> 2. Macro won't be able to handle a mutex guard for you,...

I didn't know. is that only for this crate or is valid for all Macros in Rust ?

**Comment by maciejhirsz** [comment]
There is no implementation of `From<&String>` implemented, so you'll either have to convert it to `&str` or clone it manually. The automatic conversion of `&String` -> `&str` happens only in function calls, not in macros, so that is a general thing. I can likely add those impls though.

Me not supporting mutex guards is just me, in general there is a whole bunch of other pointers/containers you can wrap your values in (Arc, Rc, RefCell...), some of which might come from 3rd party crates, so as much as I'd like to expand the API here, things are much cleaner if I just allow a fixed set of types that can automatically get cast to `JsonValue` inside the macro.
