### ISSUE TITLE
Add insert() function in JsonValue

### ISSUE THREAD

**Issue by mominul** [maciejhirsz/json-rust#161]
Implement `insert(key, value)` function for `JsonValue` to insert values in a json object.
A function for manipulating values in array `push()`/`pop()` already exists in `JsonValue`, so I think functions for manipulating objects should be in `JsonValue` too.

Update: Function for removing key from a object [already exists!](https://docs.rs/json/0.11.14/json/enum.JsonValue.html#method.remove)

I'd be eager to send a PR implementing this, I need your approval first!

**Comment by mominul** [comment]
cc @maciejhirsz

**Comment by maciejhirsz** [comment]
Sure, if you are willing to contribute a PR. Just need to do a match on the enum and use the [insert on the `Object`](https://docs.rs/json/0.11.14/json/object/struct.Object.html#method.insert).
