### ISSUE TITLE
lib.rs documentation link to compromised site

### ISSUE THREAD

**Issue by jrpascucci** [maciejhirsz/json-rust#169]
The src/lib.rs "complete documentation" link (which is not docs.rs, as the others are) goes to a website (terhix dot com) that does not appear to be legitimate any more - blocked by internet firewalls, ublock origins, and a quick check of it from a personal device just gives me spam, no content.

Other links (i.e. from readme) link 'complete documentation' to docs.rs/json/0.12.0/json/, but the docs.rs uses the value in lib.

**Comment by haukened** [comment]
It’s now the end of December. Is anyone maintaining this package?

**Comment by chrisridd** [comment]
January 2020, and the terhix site still redirects to a spam/scam site. As a newbie to rust I'm finding it very difficult to use this crate without full and proper documentation.

**Comment by maciejhirsz** [comment]
Thanks for the bump @chrisridd. Merged #170, going to do a release.

I myself use serde for most things these days, I've been thinking about deprecating the entire crate as such and just point people to serde-json instead.
