### ISSUE TITLE
Support escape sequences

### ISSUE THREAD

**Issue by Stebalien** [maciejhirsz/json-rust#2]
JSON has escape sequences (e.g. `\n`, `\uXXX`, etc.).

**Comment by SirVer** [comment]
Related: this library should be tested against something like https://github.com/json-schema-org/JSON-Schema-Test-Suite.

Unrelated: I really like the API, seems much easier to work with than serde if you do not need heavy serialization. I think this really fills a niche in the rust eco system. Well done!

**Comment by maciejhirsz** [comment]
@SirVer thanks, will make that a separate issue!
