### ISSUE TITLE
Iteration

### ISSUE THREAD

**Issue by RrayAgent** [maciejhirsz/json-rust#207]
So this isn't so much of an issue but I was trying to figure out how to iterate over a parsed JSON for like ten minutes, and I was wondering if it was possible.

**Comment by RrayAgent** [comment]
never mind, I though of how to do literally as I pressed submit issue.

**Comment by RrayAgent** [comment]
if anyone's wondering I used`for i in 0..parsed.len(){
println!("{i}");
}`

**Comment by im-n1** [comment]
@RrayAgent saved my life - the docs don't mention that at all.
