### ISSUE TITLE
Methods to check truthiness.

### ISSUE THREAD

**Issue by meh** [maciejhirsz/json-rust#24]
I'm finding myself wanting to check for truthyness instead of specific values and maybe it could be nice to have an `is_truthy` and `is_falsy` method in `JsonValue`?

It's just to avoid the `!json[key].is_null() && json[key].as_bool().unwrap_or(false)` boilerplate everywhere.

Or maybe there's already a way to do it and I'm not seeing it? Great library by the way.

**Comment by meh** [comment]
Actually I'm dumb, there's no need for the `is_null` check since in the case of `null` it would be already returning `None`, thus `false`.

Disregard everything.

**Comment by meh** [comment]
Actually I'm double dumb, that's nowhere near the same thing.

**Comment by maciejhirsz** [comment]
```rust
json[key] == true
```
will give you the same results as 
```rust
!json[key].is_null() && json[key].as_bool().unwrap_or(false)
```

That said, truthyness checks could be useful. The question here would be whether to follow JavaScript truthyness or not:

```js
!![] == true;
!!{} == true;
!!"" == false;
!!0 == false;
!!null == false;
```

Personally I find empty array or object being truthy confusing in JS.

**Comment by meh** [comment]
I'm kinda torn about that, on one hand I agree with you that `[]` and `{}` are `true` but `""` is `false` is just weird.

On the other hand changing the meaning of truthiness from JS sounds like an even bigger source of confusion.

**Comment by maciejhirsz** [comment]
I think the lesson from JS is that you should avoid type coercion altogether with `===`, except for some special cases (`thing == null` is a neat shortcut to cover `null` and `undefined`).

I was already thinking about adding an `is_empty()` method, but there the question arises whether `0` and `false` should be considered empty (initially I'd say yes). That might be a good alternative.

**Comment by maciejhirsz** [comment]
@meh `is_empty` landed. Does that + equality checks being type sensitive cover your use cases?

**Comment by meh** [comment]
I'm pretty sure it does, I'll have to try it out in the long run with the current project, I'll report back if I think there could be something more ergonomic that isn't awfully specialized for my own benefit :panda_face:

**Comment by maciejhirsz** [comment]
Cool! Going to close the issue :)
