### ISSUE TITLE
More context in error messages

### ISSUE THREAD

**Issue by emoon** [maciejhirsz/json-rust#29]
Hi,

Thanks for a great crate! 

My plan is to use it for user configuration and one issue I have is that if a user makes an error in the configuration I would like to report back a meaningful error. In this case for example an extra ```,``` has been added on ```bar```

```Json
"some_data":{
    "foo": 0,
    "bar": 42,
},
```
The error I get back is ```UnexpectedToken("BraceOff")``` which is correct but I have no idea of where the error occurs. I'm not sure if the code keeps track of line numbers but it would be very helpful if it could report on which line the error happen so I could report that back to the user.

**Comment by maciejhirsz** [comment]
Just added keeping track of current byte index in the parser. I should be able to easily derive line and column from that when an error occurs now.
