### ISSUE TITLE
Should `JsonError` and `JsonResult` just be `Error` and `Result`?

### ISSUE THREAD

**Issue by zummenix** [maciejhirsz/json-rust#38]
I'm not sure about `JsonValue`.

**Comment by maciejhirsz** [comment]
I'm not sure what the consensus of the community is about those, I personally like avoiding the confusion with built in `Result` type and `Error` trait.

Gonna leave this up for a discussion, and maybe look up what other major crates are doing.

**Comment by gsquire** [comment]
I think it's quite common to define library specific error and result types. For example the standard library uses [io::Error](https://doc.rust-lang.org/std/io/struct.Error.html) and [io::Result](https://doc.rust-lang.org/std/io/type.Result.html) for IO operations. It allows for less ambiguous types.

**Comment by maciejhirsz** [comment]
Following standard library in that regard might be a good idea. Since renaming stuff can be a breaking change, I'd schedule it for 0.9.0.
