### ISSUE TITLE
"-0" should be parsed as -0 instead of 0

### ISSUE THREAD

**Issue by dtolnay** [maciejhirsz/json-rust#43]

**Comment by maciejhirsz** [comment]
```
assert_eq!(parse("-0").unwrap(), -0f64);
assert_eq!(parse("-0").unwrap(), JsonValue::Number(-0f64));
```

Both pass fine for me.

**Comment by dtolnay** [comment]
You are right, I can't reproduce it either. I may have been confused by https://github.com/maciejhirsz/json-rust/issues/42#issuecomment-229131194: `-0f64` gets printed as `0e0` but parsing seems right.

Side note - that is actually not the right assert because `-0f64` and `0f64` are equal:

```rust
assert_eq!(-0f64, 0f64);
```

The correct one is:

```rust
assert!(!json::parse("-0").unwrap().as_f64().unwrap().is_sign_positive())
```
