### ISSUE TITLE
Update existing json structure

### ISSUE THREAD

**Issue by emoon** [maciejhirsz/json-rust#56]
Hi,
I'm using your code for my settings system. The idea with the system is to have a base set of settings and allow the user to override the default settings with own settings in a separate JSON file that can be (re)loaded.

I wonder if that is possible to do with the current code in some easy way? (I don't expect you to add something in the library to do it but I'm fine with having my own code as long as I can update the data structures)

**Comment by maciejhirsz** [comment]
You can do things like:

```rust
let is_it_on = if user_settings["foo"].as_bool().unwrap_or(defaults["foo"].as_bool().unwrap())
```

Or a more generic:

```rust
let ref value = if user_settings["foo"].is_null() { defaults["foo"] } else { user_settings["foo"] };
let index = value.as_i32().unwrap();
```

This won't handle nested structures very well though.

A deep-merge sort of a function that takes the default DOM and user settings DOM and overrides the former with the latter could do. It would have to either mutate the original DOM or do some cloning, but that shouldn't be an issue if the object is small, and/or if you only perform that when the user json changes.

**Comment by emoon** [comment]
Thanks! It's not super deep so this approach should be fine.

**Comment by maciejhirsz** [comment]
Also note that with booleans you can do `json == true` without having to unwrap everything. I might add an `or` method to increase the ergonomy of handling nulls, such as:

```rust
let is_it_on = user_settings["foo"].or(defaults["foo"]) == true;
```

I reckon it would be Rust idomatic to provide some methods that are analog to what `Option` type has available, given that `JsonValue::Null` is very similar to `Option::None`.
