### ISSUE TITLE
\x7F should be allowed in input

### ISSUE THREAD

**Issue by dtolnay** [maciejhirsz/json-rust#58]
According to [RFC7159](https://tools.ietf.org/html/rfc7159):

> All Unicode characters may be placed within the quotation marks, except for the characters that must be escaped: quotation mark, reverse solidus, and the control characters (U+0000 through U+001F).

Based on that language I would expect the following program to succeed:

```rust
extern crate json;
fn main() {
    json::parse("\"\x7F\"").unwrap();
}
```

Instead it fails with `UnexpectedCharacter { ch: '\u{7f}', line: 1, column: 2 }`.

**Comment by maciejhirsz** [comment]
Seems you are correct. Somehow the spec on the website just says "control characters", but the RFC and ECMA 404 are more specific.
