### ISSUE TITLE
Performance comparison with other existing libraries in README.md

### ISSUE THREAD

**Issue by StefanoD** [maciejhirsz/json-rust#6]
This would be interesting for many developers and a strong argument to use this library, respectively rust instead of another language.

In the comparison the version number of the respective lib should be indicated.
Especially a comparison with serd is interesting.
https://github.com/serde-rs/serde

**Comment by dtolnay** [comment]
This would be interesting, although my impression is that this library optimizes for easy API and low learning curve over performance.

We have some benchmarks of HashMap and Vec deserialization with varying types and varying sizes using both Serde and RustcDecodable at [bench_map.rs](https://github.com/serde-rs/serde/blob/d4e1ef659aaa02ac23b853fe7cd9cadc0b6ed9cf/serde_tests/benches/bench_map.rs) and [bench_vec.rs](https://github.com/serde-rs/serde/blob/d4e1ef659aaa02ac23b853fe7cd9cadc0b6ed9cf/serde_tests/benches/bench_vec.rs). I would be curious to see the same benchmarks against json-rust.

**Comment by dtolnay** [comment]
@StefanoD I tried a benchmark of deserializing [this Log object](https://github.com/serde-rs/json/blob/7343342853ba2d5286fc08d80deedb203a05f545/json_tests/benches/bench_log.rs#L947-L975). My code is at https://github.com/dtolnay/serde-json/commit/2acc39d95a228c41a77183adfc0c6c146851c29d.

| Library | Output | Time | Throughput |
| --- | --- | --- | --- |
| serde | `Log` | 5,135 ns/iter (+/- 73) | 117 MB/s |
| serde | `serde_json::Value` | 8,455 ns/iter (+/- 103) | 71 MB/s |
| rustc-serialize | `json::Json` | 12,287 ns/iter (+/- 53) | 49 MB/s |
| json-rust | `json::JsonValue` | 14,548 ns/iter (+/- 1,094) | 41 MB/s |
| rustc-serialize | `Log` | 17,170 ns/iter (+/- 219) | 35 MB/s |

Notice that Serde takes advantage of knowing the shape of the output. It is significantly faster to deserialize to `Log` compared to the enum, so json-rust has a handicap there. (That said, the opposite is true for rustc-serialize which deserializes `Log` by going to the `Json` enum first.)

**Comment by StefanoD** [comment]
@dtolnay Thank you very much. This is very impressive!
BTW: Did I note correctly, that there is json-rust to Log missing?
Could you publish similar benchmarks on your serd github webpage and compare i. e. serd with popular JSON libs?

**Comment by dtolnay** [comment]
There is a json-rust to Log missing because json-rust does not support that.

I filed https://github.com/serde-rs/json/issues/82 to add benchmarks to the serde_json readme.

**Comment by StefanoD** [comment]
Thank you, very much!

**Comment by maciejhirsz** [comment]
@dtolnay This is pretty awesome, it's good to see I've room for improvement, and it's good to know that I'm not terribly far behind to begin with and things are usable as they are. I reckon my string parsing can be much better, since I just hacked in proper escaped characters handling yesterday.

**Comment by maciejhirsz** [comment]
@dtolnay Waited a bit with this issue till I got time to look into performance. I did take a clue from Serde and reworked things to use bytes instead of characters, tests results on the same JSON as above on my machine as of 0.7.1:

Library         | Parsing                              | Serializing
----------------|--------------------------------------|----------------------------
Serde           | 10,316 ns/iter (+/- 797) = 62 MB/s   | 3,341 ns/iter (+/- 298) = 192 MB/s
json-rust       | 10,587 ns/iter (+/- 642) = 60 MB/s   | 2,685 ns/iter (+/- 314) = 239 MB/s
rustc-serialize | 15,995 ns/iter (+/- 1,179) = 40 MB/s | 5,022 ns/iter (+/- 278) = 128 MB/s

[Codez](https://github.com/maciejhirsz/json-rust/blob/8c445a13864ad2176ff95cb7a71f9b82e8532a5f/benches/lib.rs)

I haven't put in benches with the Log struct, there is a lot of boilerplate there, I might just copy over the file tomorrow. I reckon it makes sense to inform people the pros and cons of serializing to generic values vs struct, so before I push anything to README I'd rather have a complete breakdown.

Sidenote: this is probably the most nerdy fun I've had in a long while :).

**Comment by StefanoD** [comment]
Oh, please don't close this! :)
A language comparison would be interesting, also. At least a comparison with the popular Java Lib "Jackson" would be nice.
And don't forget to add the version number of the lib as performance improvements can always  be accomplished as you experienced yourself. ;)

**Comment by maciejhirsz** [comment]
Funny that you mention Jackson, since Jackson was one of the main inspirations for this (in the sense of: "oh dear, I really don't want to deal with that again").

I'll add versions. Currently the benchmarks are running via `cargo bench` on nightly, to benchmark Java things might get a bit more complicated, but I'll look into that.

**Comment by dtolnay** [comment]
Thanks for the great work on this Maciej.

I was pretty surprised by the difference in serialization time between Serde and json-rust (nicely done!) so I did some digging. It looks like the difference is 100% accounted for by two things:

- We pre-allocate a vector of 128 bytes while you pre-allocate 1024 bytes. The benchmark object was large so the larger allocation paid off.
- Serialization of u64. Your `write_digits_from_u64` is really fast. We basically use `write!(&mut writer, "{}", value)` which is astonishingly slow. I filed https://github.com/serde-rs/json/issues/84 to look into a better approach and/or contribute a fix to Rust for whatever is making `write!` slow.

**Comment by maciejhirsz** [comment]
I tried to reproduce the benchmark in Node.js (v6.1.0): https://gist.github.com/maciejhirsz/89b9813cc3fc875bd0723f6cf85dbbb9

```
Benching parse
- 5681ns per iteration
- throughput 101.56 MB/s

Benching serialize
- 4900ns per iteration
- throughput 117.76 MB/s
```

Parsing performance is really interesting given V8 has to parse things into dynamic data, not sure if my methodology is correct.

**Comment by StefanoD** [comment]
Wow, thx! That's the reason, why I wanted to compare with other libs and languages! Now you can discuss bottlenecks with other developers!

**Comment by maciejhirsz** [comment]
I suspect V8 might be doing some caching magic, I edited the gist, added this _before_ iteration:

```js
data = JSON.parse(json);
json = JSON.stringify(data);
```

Basically forcing a reset of the variables, values after:

```
Benching parse
- 6603ns per iteration
- throughput 87.38 MB/s

Benching serialize
- 5181ns per iteration
- throughput 111.35 MB/s
```

**Comment by maciejhirsz** [comment]
Fun times with 0.8.0:

```
test json_rust_parse                  ... bench:       6,670 ns/iter (+/- 507) = 90 MB/s
test json_rust_stringify              ... bench:       2,440 ns/iter (+/- 131) = 247 MB/s
test rustc_serialize_parse            ... bench:      14,554 ns/iter (+/- 815) = 41 MB/s
test rustc_serialize_stringify        ... bench:       4,523 ns/iter (+/- 357) = 133 MB/s
test rustc_serialize_struct_parse     ... bench:      20,580 ns/iter (+/- 2,144) = 29 MB/s
test rustc_serialize_struct_stringify ... bench:       4,233 ns/iter (+/- 596) = 142 MB/s
test serde_json_parse                 ... bench:       9,032 ns/iter (+/- 970) = 66 MB/s
test serde_json_stringify             ... bench:       3,415 ns/iter (+/- 254) = 177 MB/s
test serde_json_struct_parse          ... bench:       6,645 ns/iter (+/- 518) = 91 MB/s
test serde_json_struct_stringify      ... bench:       3,132 ns/iter (+/- 187) = 193 MB/s
```

🎉

**Comment by dtolnay** [comment]
Make sure to use serde_json 0.7.4 for the next run.

**Comment by maciejhirsz** [comment]
Will do, already seen the numbers, nice job!

**Comment by dtolnay** [comment]
Interestingly for stringify I get reverse results for some much larger files. Take a look [here](https://github.com/serde-rs/json-benchmark).

**Comment by maciejhirsz** [comment]
Aye, that looks reasonable considering `canada.json` has a ton of floats in it, I haven't gotten to trying to figure out how to optimize those correctly. Also I should really pull all the fail / pass jsons into my unit tests.

**Comment by dtolnay** [comment]
Ignore canada.json, I think it is a silly benchmark. But I am surprised by the other two because for the Log benchmark my results pretty much line up with yours (faster CPU but same ratios).

**Comment by maciejhirsz** [comment]
Ha, interesting. It might deal with the fact that I'm writing directly to `Vec<u8>` instead of using `<std::io::Write>`, maybe the latter deals with reallocation better. I'll investigate when I get time.

**Comment by maciejhirsz** [comment]
Looked over my stuff and made some quick very micro optimizations, particulary replacing instances where I [was writing a single byte as a slice](https://github.com/maciejhirsz/json-rust/commit/09e8df86bb8202af3ba634121c5e94d83d9d40e8?diff=unified#diff-d0b3721173a6539188b808c57c0b4b08L133) `&[u8]` instead of just `u8`.

I didn't expect much from that, but the total number of nanos is so small by now, that any deviation makes a huge difference:
```
test json_rust_parse                  ... bench:       5,800 ns/iter (+/- 984) = 104 MB/s
test json_rust_stringify              ... bench:       1,600 ns/iter (+/- 172) = 378 MB/s
```

**Comment by maciejhirsz** [comment]
@dtolnay Ok, I know what's happening - since `json-rust` can't write to `io::Write` atm, the benchmark has to first dump to an allocated `String` and then write that into a writer. I'll make a specialized generator for that (#51).

**Comment by dtolnay** [comment]
I wonder if, using [dtoa](https://github.com/dtolnay/dtoa), you could beat the [stringify time for RapidJSON](https://github.com/miloyip/nativejson-benchmark#stringify-time). I have not been able to get nativejson-benchmark running locally so I do not have numbers that are comparable but you may have better luck. It must be pretty close.

**Comment by maciejhirsz** [comment]
Numbers with dtoa:

```
======= serde_json ======= parse|stringify === parse|stringify ===
data/canada.json          51.4ms    24.1ms    36.9ms    20.4ms
data/citm_catalog.json    30.0ms     3.3ms    20.7ms     1.7ms
data/twitter.json         10.4ms     1.3ms     8.5ms     1.4ms

======= json-rust ======== parse|stringify === parse|stringify ===
data/canada.json          42.0ms    24.7ms
data/citm_catalog.json    15.9ms     2.6ms
data/twitter.json          6.8ms     1.7ms

==== rustc_serialize ===== parse|stringify === parse|stringify ===
data/canada.json          39.8ms    71.3ms    46.5ms    67.5ms
data/citm_catalog.json    26.9ms     6.0ms    32.6ms     4.1ms
data/twitter.json         13.4ms     2.9ms    17.8ms     2.6ms
```

I'll have to look into why I'm slower on twitter.json among others.

Your (re-)implementation of dtoa is using Grisu2, however there is also a [Grisu3](http://www.cs.tufts.edu/~nr/cs257/archive/florian-loitsch/printf.pdf) algorithm, which is faster but rejects 0.5% of numbers, for which a fallback can be used, that sounds like a strategy worth pursuing. Found an [implementation of it](https://github.com/lifthrasiir/rust-strconv/blob/master/src/flt2dec/strategy/grisu.rs), no idea how well it fares though.

Fun fact: the author of RapidJSON is also an author of the C++ implementation of Grisu2 _and_ the maintainer of the nativejson benchmark, kinda explains why 90% of the performance measured is how fast you can stringify floats, eh?

**Comment by maciejhirsz** [comment]
I should have spent more time researching this. Grisu3 isn't faster, it just detects when the result isn't optimal for the fallback, Grisu2 just goes through with it producing suboptimal results for some strings, which is totally fine.

**Comment by maciejhirsz** [comment]
Should update README with charts for the log benchmark, as well as the 3 benchmark tested in [json-benchmark](https://github.com/serde-rs/json-benchmark), with descriptions of what they are actually testing:

- **log.json:** pretty standard JSON object with short keys and short string or integer values. This is a relatively "easy" benchmark.
- **canada.json:** vector graphic containing vectors of vectors of floats. This benchmark is mostly testing decimal number parsing and stringifying.
- **citm_catalog:** a catalog of objects contained in one huge object using keys for ids. This benchmark tests fast key ordering in a map.
- **twitter.json:** again pretty standard JSON objects in an array. This is mostly a benchmark for sheer volume of data combined with long strings composed of unicode characters (Japanese).

**Comment by maciejhirsz** [comment]
This issue has been open forever now. The new README now links to json-benchmarks. I'd like to see improvements for performance presentation happen there. [Related issue](https://github.com/serde-rs/json-benchmark/issues/6).
