### ISSUE TITLE
map_* methods

### ISSUE THREAD

**Issue by maciejhirsz** [maciejhirsz/json-rust#65]
Instead of:

```rust
let data = object!{ foo => 10 };

let Some(num) = data["foo"].as_f64() {
    data["foo"] = (num + 1).into();
}

assert_eq(data.dump(), r#"{"foo":11}"#);
```

Do:

```rust
let data = object!{ foo => 10 };

data["foo"].map_f64(|num| num + 1);

assert_eq(data.dump(), r#"{"foo":11}"#);
```

👍  or 👎 ?

**Comment by Mark-Simulacrum** [comment]
I like the idea in general, but I'm not certain about the name. I think `map` usually doesn't change the original value, but transforms it, and returns a new value? I know that's the way it works in JS, but I'm not sure about Rust (since Rust is usually less keen on copying/cloning).

However, I don't have any suggestions for an alternate name.

**Comment by maciejhirsz** [comment]
Somehow that didn't occur to me, good point! `with_*`?

**Comment by Mark-Simulacrum** [comment]
`with_*` doesn't quite sound right to me either, maybe because of the with making me think of addition.

What do you think about `as_mut_* -> Option<&mut T>`? I'm not sure that this would even work (or be ergonomic).

**Comment by maciejhirsz** [comment]
Returning `Option<&mut T>` wouldn't work since the numbers have to be cast across types.

I was thinking about it and what I want to be able to do with it. The idea was to have an easy way to to work with numbers, but then there is a way that is maybe harder to implement, but way nicer to work with - using the [ops traits](https://doc.rust-lang.org/std/ops/#traits):

```rust
let data = object!{ foo => 10 };

data["foo"] += 1;

assert_eq(data.dump(), r#"{"foo":11}"#);
```

Gonna open that as a new issue.

**Comment by Mark-Simulacrum** [comment]
Should this be reopened since the ops traits will be a performance hit since we need to cast between types (#66)?

**Comment by maciejhirsz** [comment]
Still needs a new name though :)

**Comment by Mark-Simulacrum** [comment]
Sounds good.

**Comment by maciejhirsz** [comment]
With the advent of the new `Number` type, this is now on hold.

**Comment by maciejhirsz** [comment]
Closing in favor of #66
