### ISSUE TITLE
Consider using rust-smallvec for small vectors

### ISSUE THREAD

**Issue by StefanoD** [maciejhirsz/json-rust#71]
This could give you a performance boost.

https://github.com/servo/rust-smallvec

**Comment by maciejhirsz** [comment]
Unfortunately I don't think this works, storing small vector on the stack as array would mean that JsonValue is an infinite struct, but it does give me other ideas...

**Comment by StefanoD** [comment]
Because JsonValue has references to itself? Maybe you could use it on other places?

**Comment by StefanoD** [comment]
Here?

https://github.com/maciejhirsz/json-rust/blob/dev/src/parser.rs#L585

**Comment by maciejhirsz** [comment]
Yeah. It would be analog to `enum JsonValue { Array([JsonValue; N]), ... }` all on the stack, without a pointer anywhere to break things up a self contained struct has an infinite size. `Vec<JsonValue>` works because `Vec` is fixed size (pointer, lenght and capacity combined).

**Comment by maciejhirsz** [comment]
So, putting vectors on stack won't work, but putting [short strings](https://github.com/maciejhirsz/json-rust/blob/0.9.0/src/short.rs) on stack does. This speeds up the log benchmark by about 5%, nothing too crazy but it's something.
