### ISSUE TITLE
Parsing to structs

### ISSUE THREAD

**Issue by StefanoD** [maciejhirsz/json-rust#73]
Are there any plans to implement the ability to parse to structs?

**Comment by maciejhirsz** [comment]
Not at the moment, no.

I'd rather focus on making working with DOM as fast and easy as possible, and leave Serde for when you need structs, as the guys there do a lot of very good work regarding compiler plugins and all that.

If a demand for json-rust to implement parsing to structs becomes a thing, it is not out of the question, but I see that as a more of a 2.0 nice to have kind of a feature at this point.
