### ISSUE TITLE
Ability to "pretty print" serialized JSON

### ISSUE THREAD

**Issue by imp** [maciejhirsz/json-rust#8]
I see that `json::codegen::Generator` can produce pretty print format. However, this seems to be a private interface. And `stringify()`, which is public, unconditionally initialises `Generator::minify` to `false`.

This is to request user controllable "pretty print" serialization formatting.

**Comment by maciejhirsz** [comment]
Yep, I pulled the Generator out of my JS parser which can do pretty printing, haven't tested it but in theory it should be just an interface addition.

**Comment by maciejhirsz** [comment]
@nshtg moving the discussion here, initial implementation here:
https://github.com/maciejhirsz/json-rust/commit/352e19d6543b70fabc183b37a7729460f9b21fbd

Not sure if this is better than having an integer as a param on `pretty()`, but technically it allows you to use tabs instead of spaces if you are so inclined.

**Comment by nshtg** [comment]
I would definitely prefer an integer based solution (tabs are evil anyways, who still uses them?). 

This is one of the situation in which I miss function overloading (like in c++). Or default params for functions.

I started with Rust 2 days ago, can we implement "both" solutions using Traits? One trait defining pretty(&str) and the other defining pretty(usize)?

**Comment by maciejhirsz** [comment]
Went with `u16` for number of spaces as it was in your original commit, kept the methods separated so `dump` takes no arguments and `pretty` takes the indentation size. Calling `value.pretty(0)` might still make sense if you want new lines but for some reason don't want indents.

Thanks guys!
