### ISSUE TITLE
Provide utility for getting non-floating point numbers.

### ISSUE THREAD

**Issue by Mark-Simulacrum** [maciejhirsz/json-rust#9]
At least an `as_u64()` method would help to avoid the current state where I often need to `*parsed as u64` after getting a number.

Serde provides convenience `i/u64` and `f64` getters.

Serde's implementation of these getters, in case it helps: https://github.com/serde-rs/json/blob/master/json/src/value.rs#L280-L309.

**Comment by maciejhirsz** [comment]
@Mark-Simulacrum I was thinking about implementing reverse `Into`, e.g.:

```rust
let json_num: JsonValue = 10.into(); // this works already
let raw_num: i32 = json_num.into();
```

Problem here is that `into()` can't fail, so I'd have to default to zero. It could be done with `Option<_>` instead, but that might feel clunky. Thoughts?

**Comment by maciejhirsz** [comment]
I wanted to suggest using `Into` trait, but forgot it takes an owned value. I might do a generic method that can cast to any type though, something like:

```
let number: i32 = json.value();
```

The problem here is that I'd have to default numbers to `0`, inferencing `Result` or `Option` might feel clunky without dedicated methods.

**Comment by Mark-Simulacrum** [comment]
It may be worth pointing out that Serde returns owned numbers AFAICT, not references to them--this may solve the `Into` trait problem, but I'm not sure if they copy/clone the number before returning.

**Comment by maciejhirsz** [comment]
Returning owned numbers isn't a problem since they are copy. The problem is rather that doing `value.into()` consumes `value`, and it makes it unusable if you only have a reference to `value` (so things like `data["foo"].into()` won't work).
