### ISSUE TITLE
Add useful traits to errors

### ISSUE THREAD

**Issue by kless** [maciejhirsz/json-rust#99]
Please add `#[derive(Debug, PartialEq, Eq)]` so the error could be compared in tests of other libraries/apps that use your library, or be copied.
Thanks in advance!

https://www.reddit.com/r/rust/comments/5d8frm/traits_derived_in_errors/

**Comment by maciejhirsz** [comment]
Thanks for pointing this out!

**Comment by maciejhirsz** [comment]
Closed with: https://github.com/maciejhirsz/json-rust/commit/a6bbcc3adc813ff26190012a677a13f2a06b5464
